### ISSUE TITLE
what is the meaning of the self.temperature used in the binarization process of weights?

### ISSUE THREAD

**Issue by Alexrich961210** [hpi-xnor/BNext#5]

**Comment by NicoNico6** [comment]
Thanks for your attention to this work.

As described in the paper, we use the progressive weight binarization technique [0] and the self.temperature in HardBinaryConv class controls the binarization degree during training. It starts from 1.0 and evolves to 0.0 following an exponential decay scheme.

Wish this is helpful for you. 

[0] BoolNet: Minimizing The Energy Consumption of Binary Neural Networks
